<p>QUERIDO SOCIO COMERCIAL TE ENVÍAMOS ESTA LIGA PARA DARTE DE ALTA COMO PROVEEDOR DENTRO DE NUESTRO CORPORATIVO, TE SUGERIMOS LEER PRIMERO TODO EL FORMULARIO PARA QUE PUEDAS REUNIR LOS DOCUMENTOS REQUERIDOS Y DESPUÉS PUEDAS SUBIRLOS A LA PLATAFORMA.								
DE ACUERDO A LAS NORMAS LEGALES ESTABLECIDAS POR EL GOBIERNO, REQUERIMOS CUMPLIR CON TODA ESTA DOCUMENTACION, POR LO QUE TE PEDIMOS MANTENERLA ACTUALIZADA								
PARA TENER UNA RELACIÓN COMERCIAL DURADERA Y SANA.								
CUALQUIER DUDA PUEDES CONTACTARNOS EN EL SIGUIENTE TEL: 55 55 63 83 00								 </p>