<?php 






$ROWDirEmpresa = $proveedoresC->variable_DIRECCIONP1($idPROV);

$ROWotrosp12= array('VALIDADIRECCIONEP1' =>'VALIDADIRECCIONEP1');
$direcciondeempresaporcentaje =$conexion->contadorporcentaje($ROWDirEmpresa,$ROWotrosp12);

$P_NOMBRE_COMERCIAL_EMPRESA = isset($ROWDirEmpresa["P_NOMBRE_COMERCIAL_EMPRESA"])?$ROWDirEmpresa["P_NOMBRE_COMERCIAL_EMPRESA"]:"";
$P_NOMBRE_FISCAL_RS_EMPRESA = isset($ROWDirEmpresa["P_NOMBRE_FISCAL_RS_EMPRESA"])?$ROWDirEmpresa["P_NOMBRE_FISCAL_RS_EMPRESA"]:"";
$P_RFC_MTDP = isset($ROWDirEmpresa["P_RFC_MTDP"])?$ROWDirEmpresa["P_RFC_MTDP"]:"";
$P_REGIMEN_FISCAL_MTDP = isset($ROWDirEmpresa["P_REGIMEN_FISCAL_MTDP"])?$ROWDirEmpresa["P_REGIMEN_FISCAL_MTDP"]:"";
$_P_METODO_DE_PAGO = isset($ROWDirEmpresa["_P_METODO_DE_PAGO"])?$ROWDirEmpresa["_P_METODO_DE_PAGO"]:"";
$P_FORMADE_PAGO = isset($ROWDirEmpresa["P_FORMADE_PAGO"])?$ROWDirEmpresa["P_FORMADE_PAGO"]:"";
$P_USO_CFDI = isset($ROWDirEmpresa["P_USO_CFDI"])?$ROWDirEmpresa["P_USO_CFDI"]:"";
$FISICA_MORAL = isset($ROWDirEmpresa["FISICA_MORAL"])?$ROWDirEmpresa["FISICA_MORAL"]:"";
$P_DIRECCION_FISCAL_EMPRESA = isset($ROWDirEmpresa["P_DIRECCION_FISCAL_EMPRESA"])?$ROWDirEmpresa["P_DIRECCION_FISCAL_EMPRESA"]:"";
$P_EDIFICIO_EMPRESA = isset($ROWDirEmpresa["P_EDIFICIO_EMPRESA"])?$ROWDirEmpresa["P_EDIFICIO_EMPRESA"]:"";
$P_CALLE_EMPRESA = isset($ROWDirEmpresa["P_CALLE_EMPRESA"])?$ROWDirEmpresa["P_CALLE_EMPRESA"]:"";
$P_NUMERO_EXTERIOR_EMPRESA = isset($ROWDirEmpresa["P_NUMERO_EXTERIOR_EMPRESA"])?$ROWDirEmpresa["P_NUMERO_EXTERIOR_EMPRESA"]:"";
$P_NUMERO_INTERIOR_EMPRESA = isset($ROWDirEmpresa["P_NUMERO_INTERIOR_EMPRESA"])?$ROWDirEmpresa["P_NUMERO_INTERIOR_EMPRESA"]:"";
$P_NUMERO_OFICINA_EMPRESA = isset($ROWDirEmpresa["P_NUMERO_OFICINA_EMPRESA"])?$ROWDirEmpresa["P_NUMERO_OFICINA_EMPRESA"]:"";
$P_COLONIA_EMPRESA = isset($ROWDirEmpresa["P_COLONIA_EMPRESA"])?$ROWDirEmpresa["P_COLONIA_EMPRESA"]:"";
$P_ALCALDIA_EMPRESA = isset($ROWDirEmpresa["P_ALCALDIA_EMPRESA"])?$ROWDirEmpresa["P_ALCALDIA_EMPRESA"]:"";
$P_C_P_EMPRESA = isset($ROWDirEmpresa["P_C_P_EMPRESA"])?$ROWDirEmpresa["P_C_P_EMPRESA"]:"";
$P_CIUDAD_EMPRESA = isset($ROWDirEmpresa["P_CIUDAD_EMPRESA"])?$ROWDirEmpresa["P_CIUDAD_EMPRESA"]:"";
$P_ESTADO_EMPRESA = isset($ROWDirEmpresa["P_ESTADO_EMPRESA"])?$ROWDirEmpresa["P_ESTADO_EMPRESA"]:"";
$P_PAIS_EMPRESA = isset($ROWDirEmpresa["P_PAIS_EMPRESA"])?$ROWDirEmpresa["P_PAIS_EMPRESA"]:"";
$dircasa11 = isset($ROWDirEmpresa["dircasa11"])?$ROWDirEmpresa["dircasa11"]:"";
$P_UBICACION_MAPA_1 = isset($ROWDirEmpresa["P_UBICACION_MAPA_1"])?$ROWDirEmpresa["P_UBICACION_MAPA_1"]:"";
$P_TELEFONO_1_EMPRESA = isset($ROWDirEmpresa["P_TELEFONO_1_EMPRESA"])?$ROWDirEmpresa["P_TELEFONO_1_EMPRESA"]:"";
$P_TELEFONO_2_EMPRESA = isset($ROWDirEmpresa["P_TELEFONO_2_EMPRESA"])?$ROWDirEmpresa["P_TELEFONO_2_EMPRESA"]:"";
$P_WHATSAPP_EMPRESA_1 = isset($ROWDirEmpresa["P_WHATSAPP_EMPRESA_1"])?$ROWDirEmpresa["P_WHATSAPP_EMPRESA_1"]:"";
$P_IMAIL_EMPRESA = isset($ROWDirEmpresa["P_IMAIL_EMPRESA"])?$ROWDirEmpresa["P_IMAIL_EMPRESA"]:"";
$P_PAGINA_WEB_EMPRESA = isset($ROWDirEmpresa["P_PAGINA_WEB_EMPRESA"])?$ROWDirEmpresa["P_PAGINA_WEB_EMPRESA"]:"";
$P_NOMBRE_APP_EMPRESA = isset($ROWDirEmpresa["P_NOMBRE_APP_EMPRESA"])?$ROWDirEmpresa["P_NOMBRE_APP_EMPRESA"]:"";





/* CONTACTO VENTAS */

/*
$ROWcontactp = $proveedoresC->variable_contactoventasP();

$ROWotrosp12= array('validaNOMBRECONTACTO1' =>'validaNOMBRECONTACTO1');
$contactosventasproveedoresporcentaje =$conexion->contadorporcentaje($ROWcontactp,$ROWotrosp12);


$P_NOMBRE_DEL_CONTACTO_V = isset($ROWcontactp["P_NOMBRE_DEL_CONTACTO_V"])?$ROWcontactp["P_NOMBRE_DEL_CONTACTO_V"]:"";
$P_NOMBRE_DEL_CONTACTO_V_2 = isset($ROWcontactp["P_NOMBRE_DEL_CONTACTO_V_2"])?$ROWcontactp["P_NOMBRE_DEL_CONTACTO_V_2"]:"";
$P_NOMBRE_DEL_CONTACTO_V_3 = isset($ROWcontactp["P_NOMBRE_DEL_CONTACTO_V_3"])?$ROWcontactp["P_NOMBRE_DEL_CONTACTO_V_3"]:"";
$P_NUMERO_CEL_CONTACTO_V = isset($ROWcontactp["P_NUMERO_CEL_CONTACTO_V"])?$ROWcontactp["P_NUMERO_CEL_CONTACTO_V"]:"";
$P_NUMERO_CEL_CONTACTO_V_2 = isset($ROWcontactp["P_NUMERO_CEL_CONTACTO_V_2"])?$ROWcontactp["P_NUMERO_CEL_CONTACTO_V_2"]:"";
$P_NUMERO_CEL_CONTACTO_V_3 = isset($ROWcontactp["P_NUMERO_CEL_CONTACTO_V_3"])?$ROWcontactp["P_NUMERO_CEL_CONTACTO_V_3"]:"";
$P_NUMERO_OFICINA_V = isset($ROWcontactp["P_NUMERO_OFICINA_V"])?$ROWcontactp["P_NUMERO_OFICINA_V"]:"";
$P_NUMERO_OFICINA_V_2 = isset($ROWcontactp["P_NUMERO_OFICINA_V_2"])?$ROWcontactp["P_NUMERO_OFICINA_V_2"]:"";
$P_NUMERO_OFICINA_V_3 = isset($ROWcontactp["P_NUMERO_OFICINA_V_3"])?$ROWcontactp["P_NUMERO_OFICINA_V_3"]:"";
$P_NUMERO_EXTENSION_V = isset($ROWcontactp["P_NUMERO_EXTENSION_V"])?$ROWcontactp["P_NUMERO_EXTENSION_V"]:"";
$P_NUMERO_EXTENSION_V_2 = isset($ROWcontactp["P_NUMERO_EXTENSION_V_2"])?$ROWcontactp["P_NUMERO_EXTENSION_V_2"]:"";
$P_NUMERO_EXTENSION_V_3 = isset($ROWcontactp["P_NUMERO_EXTENSION_V_3"])?$ROWcontactp["P_NUMERO_EXTENSION_V_3"]:"";
$P_IMAIL_CONTACTO_V = isset($ROWcontactp["P_IMAIL_CONTACTO_V"])?$ROWcontactp["P_IMAIL_CONTACTO_V"]:"";
$P_IMAIL_CONTACTO_V_2 = isset($ROWcontactp["P_IMAIL_CONTACTO_V_2"])?$ROWcontactp["P_IMAIL_CONTACTO_V_2"]:"";
$P_IMAIL_CONTACTO_EDE_V_3 = isset($ROWcontactp["P_IMAIL_CONTACTO_EDE_V_3"])?$ROWcontactp["P_IMAIL_CONTACTO_EDE_V_3"]:"";
$validaNOMBRECONTACTO1 = isset($ROWcontactp["validaNOMBRECONTACTO1"])?$ROWcontactp["validaNOMBRECONTACTO1"]:""; 
*/

/* CONTACTO VENTAS 2*/


$ROWcontactp2 = $proveedoresC->variable_contactoventasP2();

$ROWotrosp12= array('validaNOMBRECONTACTO2' =>'validaNOMBRECONTACTO2');
$contactosventasproveedoresporcentaje2 =$conexion->contadorporcentaje($ROWcontactp2,$ROWotrosp12);



$P_NOMBRE_DEL_CONTACTO_CF = isset($ROWcontactp2["P_NOMBRE_DEL_CONTACTO_CF"])?$ROWcontactp2["P_NOMBRE_DEL_CONTACTO_CF"]:"";
$P_NOMBRE_DEL_CONTACTO_NP = isset($ROWcontactp2["P_NOMBRE_DEL_CONTACTO_NP"])?$ROWcontactp2["P_NOMBRE_DEL_CONTACTO_NP"]:"";
$P_NOMBRE_DEL_CONTACTO_EDE = isset($ROWcontactp2["P_NOMBRE_DEL_CONTACTO_EDE"])?$ROWcontactp2["P_NOMBRE_DEL_CONTACTO_EDE"]:"";
$P_NUMERO_CEL_CONTACTO_CF = isset($ROWcontactp2["P_NUMERO_CEL_CONTACTO_CF"])?$ROWcontactp2["P_NUMERO_CEL_CONTACTO_CF"]:"";
$P_NUMERO_CEL_CONTACTO_NP = isset($ROWcontactp2["P_NUMERO_CEL_CONTACTO_NP"])?$ROWcontactp2["P_NUMERO_CEL_CONTACTO_NP"]:"";
$P_NUMERO_CEL_CONTACTO_EDE = isset($ROWcontactp2["P_NUMERO_CEL_CONTACTO_EDE"])?$ROWcontactp2["P_NUMERO_CEL_CONTACTO_EDE"]:"";
$P_NUMERO_OFICINA_CF = isset($ROWcontactp2["P_NUMERO_OFICINA_CF"])?$ROWcontactp2["P_NUMERO_OFICINA_CF"]:"";
$P_NUMERO_OFICINA_NP = isset($ROWcontactp2["P_NUMERO_OFICINA_NP"])?$ROWcontactp2["P_NUMERO_OFICINA_NP"]:"";
$P_NUMERO_OFICINA_EDE = isset($ROWcontactp2["P_NUMERO_OFICINA_EDE"])?$ROWcontactp2["P_NUMERO_OFICINA_EDE"]:"";
$P_NUMERO_EXTENSION_CF = isset($ROWcontactp2["P_NUMERO_EXTENSION_CF"])?$ROWcontactp2["P_NUMERO_EXTENSION_CF"]:"";
$P_NUMERO_EXTENSION_NP = isset($ROWcontactp2["P_NUMERO_EXTENSION_NP"])?$ROWcontactp2["P_NUMERO_EXTENSION_NP"]:"";
$P_NUMERO_EXTENSION_EDE = isset($ROWcontactp2["P_NUMERO_EXTENSION_EDE"])?$ROWcontactp2["P_NUMERO_EXTENSION_EDE"]:"";
$P_IMAIL_CONTACTO_CF = isset($ROWcontactp2["P_IMAIL_CONTACTO_CF"])?$ROWcontactp2["P_IMAIL_CONTACTO_CF"]:"";
$P_IMAIL_CONTACTO_NP = isset($ROWcontactp2["P_IMAIL_CONTACTO_NP"])?$ROWcontactp2["P_IMAIL_CONTACTO_NP"]:"";
$P_IMAIL_CONTACTO_EDE = isset($ROWcontactp2["P_IMAIL_CONTACTO_EDE"])?$ROWcontactp2["P_IMAIL_CONTACTO_EDE"]:"";
$validaNOMBRECONTACTO2 = isset($ROWcontactp2["validaNOMBRECONTACTO2"])?$ROWcontactp2["validaNOMBRECONTACTO2"]:"";

/* CONTACTO VENTAS 2*/


$ROWcontactp3 = $proveedoresC->variable_contactoventasP3();

$ROWotrosp12= array('validaNOMBRECONTACTO3' =>'validaNOMBRECONTACTO3');
$contactosventasproveedoresporcentaje3 =$conexion->contadorporcentaje($ROWcontactp3,$ROWotrosp12);


$P_NOMBRE_DEL_CONTACTO_CF_2 = isset($ROWcontactp3["P_NOMBRE_DEL_CONTACTO_CF_2"])?$ROWcontactp3["P_NOMBRE_DEL_CONTACTO_CF_2"]:"";
$P_NOMBRE_DEL_CONTACTO_NP_2 = isset($ROWcontactp3["P_NOMBRE_DEL_CONTACTO_NP_2"])?$ROWcontactp3["P_NOMBRE_DEL_CONTACTO_NP_2"]:"";
$P_NOMBRE_DEL_CONTACTO_EDE_2 = isset($ROWcontactp3["P_NOMBRE_DEL_CONTACTO_EDE_2"])?$ROWcontactp3["P_NOMBRE_DEL_CONTACTO_EDE_2"]:"";
$P_NUMERO_CEL_CONTACTO_CF_2 = isset($ROWcontactp3["P_NUMERO_CEL_CONTACTO_CF_2"])?$ROWcontactp3["P_NUMERO_CEL_CONTACTO_CF_2"]:"";
$P_NUMERO_CEL_CONTACTO_NP_2 = isset($ROWcontactp3["P_NUMERO_CEL_CONTACTO_NP_2"])?$ROWcontactp3["P_NUMERO_CEL_CONTACTO_NP_2"]:"";
$P_NUMERO_CEL_CONTACTO_EDE_2 = isset($ROWcontactp3["P_NUMERO_CEL_CONTACTO_EDE_2"])?$ROWcontactp3["P_NUMERO_CEL_CONTACTO_EDE_2"]:"";
$P_NUMERO_OFICINA_CF_2 = isset($ROWcontactp3["P_NUMERO_OFICINA_CF_2"])?$ROWcontactp3["P_NUMERO_OFICINA_CF_2"]:"";
$P_NUMERO_OFICINA_NP_2 = isset($ROWcontactp3["P_NUMERO_OFICINA_NP_2"])?$ROWcontactp3["P_NUMERO_OFICINA_NP_2"]:"";
$P_NUMERO_OFICINA_EDE_2 = isset($ROWcontactp3["P_NUMERO_OFICINA_EDE_2"])?$ROWcontactp3["P_NUMERO_OFICINA_EDE_2"]:"";
$P_NUMERO_EXTENSION_CF_2 = isset($ROWcontactp3["P_NUMERO_EXTENSION_CF_2"])?$ROWcontactp3["P_NUMERO_EXTENSION_CF_2"]:"";
$P_NUMERO_EXTENSION_NP_2 = isset($ROWcontactp3["P_NUMERO_EXTENSION_NP_2"])?$ROWcontactp3["P_NUMERO_EXTENSION_NP_2"]:"";
$P_NUMERO_EXTENSION_EDE_2 = isset($ROWcontactp3["P_NUMERO_EXTENSION_EDE_2"])?$ROWcontactp3["P_NUMERO_EXTENSION_EDE_2"]:"";
$P_IMAIL_CONTACTO_CF_2 = isset($ROWcontactp3["P_IMAIL_CONTACTO_CF_2"])?$ROWcontactp3["P_IMAIL_CONTACTO_CF_2"]:"";
$P_IMAIL_CONTACTO_NP_2 = isset($ROWcontactp3["P_IMAIL_CONTACTO_NP_2"])?$ROWcontactp3["P_IMAIL_CONTACTO_NP_2"]:"";
$P_IMAIL_CONTACTO_EDE_2 = isset($ROWcontactp3["P_IMAIL_CONTACTO_EDE_2"])?$ROWcontactp3["P_IMAIL_CONTACTO_EDE_2"]:"";
$validaNOMBRECONTACTO3 = isset($ROWcontactp3["validaNOMBRECONTACTO3"])?$ROWcontactp3["validaNOMBRECONTACTO3"]:""; 




/* INFORMACION PRODUCTOS SERVICIOS */

$ROWprodservicios = $proveedoresC->variable_productosservicios();

$ROWotrosp12= array('validaINFOPRODSERV' =>'validaINFOPRODSERV', 'CALIFICACIONPSG' => 'CALIFICACIONPSG', 'CALIFICACION_TR' => 'CALIFICACION_TR',
 'MOTIVO_CALIFICACION' => 'MOTIVO_CALIFICACION', 'PFECHA_ULTIMACOMPRA' =>'PFECHA_ULTIMACOMPRA', 'PFECHA_ACTUA_DOCUM' => 'PFECHA_ACTUA_DOCUM');
$informacionproductosserviciosporcentaje =$conexion->contadorporcentaje($ROWprodservicios,$ROWotrosp12);




$PROVEEDOR_DE_EPC = isset($ROWprodservicios["PROVEEDOR_DE_EPC"])?$ROWprodservicios["PROVEEDOR_DE_EPC"]:"";
$PROVEEDOR_DE_INNOVAC = isset($ROWprodservicios["PROVEEDOR_DE_INNOVAC"])?$ROWprodservicios["PROVEEDOR_DE_INNOVAC"]:"";
$PROVEEDOR_DE_JUST = isset($ROWprodservicios["PROVEEDOR_DE_JUST"])?$ROWprodservicios["PROVEEDOR_DE_JUST"]:"";
$CALIFICACIONPSG = isset($ROWprodservicios["CALIFICACIONPSG"])?$ROWprodservicios["CALIFICACIONPSG"]:"";
$CALIFICACION_TR = isset($ROWprodservicios["CALIFICACION_TR"])?$ROWprodservicios["CALIFICACION_TR"]:"";
$MOTIVO_CALIFICACION = isset($ROWprodservicios["MOTIVO_CALIFICACION"])?$ROWprodservicios["MOTIVO_CALIFICACION"]:"";
$CIUDAD_SERVICIO = isset($ROWprodservicios["CIUDAD_SERVICIO"])?$ROWprodservicios["CIUDAD_SERVICIO"]:"";
$PAIS_SERVICIO = isset($ROWprodservicios["PAIS_SERVICIO"])?$ROWprodservicios["PAIS_SERVICIO"]:"";
$PFECHA_ULTIMACOMPRA = isset($ROWprodservicios["PFECHA_ULTIMACOMPRA"])?$ROWprodservicios["PFECHA_ULTIMACOMPRA"]:"";
$PFECHA_ACTUA_DOCUM = isset($ROWprodservicios["PFECHA_ACTUA_DOCUM"])?$ROWprodservicios["PFECHA_ACTUA_DOCUM"]:"";
$PCONTACTADO_POR = isset($ROWprodservicios["PCONTACTADO_POR"])?$ROWprodservicios["PCONTACTADO_POR"]:"";
$P_OTRO = isset($ROWprodservicios["P_OTRO"])?$ROWprodservicios["P_OTRO"]:"";
$PLIGA_FOTOS_VIDEOS = isset($ROWprodservicios["PLIGA_FOTOS_VIDEOS"])?$ROWprodservicios["PLIGA_FOTOS_VIDEOS"]:"";
$PRODUCTO_O_SERVICIO = isset($ROWprodservicios["PRODUCTO_O_SERVICIO"])?$ROWprodservicios["PRODUCTO_O_SERVICIO"]:"";
$PRODUCTO_O_SERVICIO_2 = isset($ROWprodservicios["PRODUCTO_O_SERVICIO_2"])?$ROWprodservicios["PRODUCTO_O_SERVICIO_2"]:"";
$PRODUCTO_O_SERVICIO_3 = isset($ROWprodservicios["PRODUCTO_O_SERVICIO_3"])?$ROWprodservicios["PRODUCTO_O_SERVICIO_3"]:"";
$PRODUCTO_O_SERVICIO_4 = isset($ROWprodservicios["PRODUCTO_O_SERVICIO_4"])?$ROWprodservicios["PRODUCTO_O_SERVICIO_4"]:"";
$PRODUCTO_O_SERVICIO_5 = isset($ROWprodservicios["PRODUCTO_O_SERVICIO_5"])?$ROWprodservicios["PRODUCTO_O_SERVICIO_5"]:"";
$PRODUCTO_O_SERVICIO_6 = isset($ROWprodservicios["PRODUCTO_O_SERVICIO_6"])?$ROWprodservicios["PRODUCTO_O_SERVICIO_6"]:"";
$PRODUCTO_O_SERVICIO_7 = isset($ROWprodservicios["PRODUCTO_O_SERVICIO_7"])?$ROWprodservicios["PRODUCTO_O_SERVICIO_7"]:"";
$PRODUCTO_O_SERVICIO_8 = isset($ROWprodservicios["PRODUCTO_O_SERVICIO_8"])?$ROWprodservicios["PRODUCTO_O_SERVICIO_8"]:"";
$F_PPRESENTACION = isset($ROWprodservicios["F_PPRESENTACION"])?$ROWprodservicios["F_PPRESENTACION"]:"";
$F_PFOTOS_PRODUCTOS = isset($ROWprodservicios["F_PFOTOS_PRODUCTOS"])?$ROWprodservicios["F_PFOTOS_PRODUCTOS"]:"";


/* INFORMACION PRODUCTOS SERVICIOS */

$ROWdoctos = $proveedoresC->variablesadjuntosproveedor();

$ROWotrosp12= array('validaINFOPRODSERV' =>'validaINFOPRODSERV',
'F_PADJUNTAR_OTRO_DOCUMENTO' =>'F_PADJUNTAR_OTRO_DOCUMENTO','F_PADJUNTAR_OTRO_DOCUMENTO_1' =>'F_PADJUNTAR_OTRO_DOCUMENTO_1','F_PADJUNTAR_OTRO_DOCUMENTO_2' =>'F_PADJUNTAR_OTRO_DOCUMENTO_2','F_PADJUNTAR_OTRO_DOCUMENTO_3' =>'F_PADJUNTAR_OTRO_DOCUMENTO_3');
$datosproveedoresadjuntos =$conexion->contadorporcentaje($ROWdoctos,$ROWotrosp12);


$F_PDESCARGAR_CONTRATO_PROVEEDORES = isset($ROWdoctos["F_PDESCARGAR_CONTRATO_PROVEEDORES"])?$ROWdoctos["F_PDESCARGAR_CONTRATO_PROVEEDORES"]:"";
$F_PADJUNTAR_CONTRATO_FIRMADO = isset($ROWdoctos["F_PADJUNTAR_CONTRATO_FIRMADO"])?$ROWdoctos["F_PADJUNTAR_CONTRATO_FIRMADO"]:"";
$F_PADJUNTAR_CONTRATO_FIRMADO_2 = isset($ROWdoctos["F_PADJUNTAR_CONTRATO_FIRMADO_2"])?$ROWdoctos["F_PADJUNTAR_CONTRATO_FIRMADO_2"]:"";
$F_PADJUNTAR_CONVENIOS = isset($ROWdoctos["F_PADJUNTAR_CONVENIOS"])?$ROWdoctos["F_PADJUNTAR_CONVENIOS"]:"";
$F_PADJUNTAR_CONSTANCIA_DE_SITUACION_FISCAL = isset($ROWdoctos["F_PADJUNTAR_CONSTANCIA_DE_SITUACION_FISCAL"])?$ROWdoctos["F_PADJUNTAR_CONSTANCIA_DE_SITUACION_FISCAL"]:"";
$F_PADJUNTAR_OPINION_CUMPLIMIENTO = isset($ROWdoctos["F_PADJUNTAR_OPINION_CUMPLIMIENTO"])?$ROWdoctos["F_PADJUNTAR_OPINION_CUMPLIMIENTO"]:"";
$F_PADJUNTAR_REGIMEN_FISCAL = isset($ROWdoctos["F_PADJUNTAR_REGIMEN_FISCAL"])?$ROWdoctos["F_PADJUNTAR_REGIMEN_FISCAL"]:"";
$F_PADJUNTAR_COMPROBANTE_DE_DOMICILIO = isset($ROWdoctos["F_PADJUNTAR_COMPROBANTE_DE_DOMICILIO"])?$ROWdoctos["F_PADJUNTAR_COMPROBANTE_DE_DOMICILIO"]:"";
$F_PADJUNTAR_ESTADO_CUENTA_BANCARIO = isset($ROWdoctos["F_PADJUNTAR_ESTADO_CUENTA_BANCARIO"])?$ROWdoctos["F_PADJUNTAR_ESTADO_CUENTA_BANCARIO"]:"";
$F_PADJUNTAR_ACTA_CONSTITUTIVA = isset($ROWdoctos["F_PADJUNTAR_ACTA_CONSTITUTIVA"])?$ROWdoctos["F_PADJUNTAR_ACTA_CONSTITUTIVA"]:"";
$F_PADJUNTAR_PODER_NOTARIAL_REPRESENTANTE_LEGAL = isset($ROWdoctos["F_PADJUNTAR_PODER_NOTARIAL_REPRESENTANTE_LEGAL"])?$ROWdoctos["F_PADJUNTAR_PODER_NOTARIAL_REPRESENTANTE_LEGAL"]:"";
$F_PADJUNTAR_IDENTIFICACION_REPRESENTANTE_LEGAL = isset($ROWdoctos["F_PADJUNTAR_IDENTIFICACION_REPRESENTANTE_LEGAL"])?$ROWdoctos["F_PADJUNTAR_IDENTIFICACION_REPRESENTANTE_LEGAL"]:"";
$F_PADJUNTAR_OTRO_DOCUMENTO = isset($ROWdoctos["F_PADJUNTAR_OTRO_DOCUMENTO"])?$ROWdoctos["F_PADJUNTAR_OTRO_DOCUMENTO"]:"";
$F_PADJUNTAR_OTRO_DOCUMENTO_1 = isset($ROWdoctos["F_PADJUNTAR_OTRO_DOCUMENTO_1"])?$ROWdoctos["F_PADJUNTAR_OTRO_DOCUMENTO_1"]:"";
$F_PADJUNTAR_OTRO_DOCUMENTO_2 = isset($ROWdoctos["F_PADJUNTAR_OTRO_DOCUMENTO_2"])?$ROWdoctos["F_PADJUNTAR_OTRO_DOCUMENTO_2"]:"";
$F_PADJUNTAR_OTRO_DOCUMENTO_3 = isset($ROWdoctos["F_PADJUNTAR_OTRO_DOCUMENTO_3"])?$ROWdoctos["F_PADJUNTAR_OTRO_DOCUMENTO_3"]:"";
$ADJUNTAR_CONTRATO_INFORMACION= isset($ROWdoctos["ADJUNTAR_CONTRATO_INFORMACION"])?$ROWdoctos["ADJUNTAR_CONTRATO_INFORMACION"]:"";




/* otros documentos */













$ROWdatosbancarios2 = $proveedoresC->variable_DATOSBANCARIOS2();

$ROWotrosp12o= array('validaDATOSBANCARIOS2' =>'validaDATOSBANCARIOS2');
$datosporcentajeDATOSBANCARIOS2 =$conexion->contadorporcentaje($ROWdatosbancarios2,$ROWotrosp12o);

$P_TIPO_DE_MONEDA_2 = isset($ROWdatosbancarios2["P_TIPO_DE_MONEDA_2"])?$ROWdatosbancarios2["P_TIPO_DE_MONEDA_2"]:"";
$P_INSTITUCION_FINANCIERA_2 = isset($ROWdatosbancarios2["P_INSTITUCION_FINANCIERA_2"])?$ROWdatosbancarios2["P_INSTITUCION_FINANCIERA_2"]:"";
$P_NUMERO_DE_CUENTA_DB_2 = isset($ROWdatosbancarios2["P_NUMERO_DE_CUENTA_DB_2"])?$ROWdatosbancarios2["P_NUMERO_DE_CUENTA_DB_2"]:"";
$P_NUMERO_CLABE_2 = isset($ROWdatosbancarios2["P_NUMERO_CLABE_2"])?$ROWdatosbancarios2["P_NUMERO_CLABE_2"]:"";
$P_NUMERO_DE_SUCURSAL_2 = isset($ROWdatosbancarios2["P_NUMERO_DE_SUCURSAL_2"])?$ROWdatosbancarios2["P_NUMERO_DE_SUCURSAL_2"]:"";
$P_NUMERO_IBAN_2 = isset($ROWdatosbancarios2["P_NUMERO_IBAN_2"])?$ROWdatosbancarios2["P_NUMERO_IBAN_2"]:"";
$P_NUMERO_CUENTA_SWIFT_2 = isset($ROWdatosbancarios2["P_NUMERO_CUENTA_SWIFT_2"])?$ROWdatosbancarios2["P_NUMERO_CUENTA_SWIFT_2"]:"";
$validaDATOSBANCARIOS2 = isset($ROWdatosbancarios2["validaDATOSBANCARIOS2"])?$ROWdatosbancarios2["validaDATOSBANCARIOS2"]:"";  






$REFERENCIASCOMERCIALES2 = $proveedoresC->variable_REFERENCIASCOMERCIALES2();

$ROWotrosp12o= array('validaREFERENCIASCOMERCIALES2' =>'validaREFERENCIASCOMERCIALES2');
$datosREFERENCIASCOMERCIALES2 =$conexion->contadorporcentaje($REFERENCIASCOMERCIALES2,$ROWotrosp12o);




$P_NOMBRE_EMPRESA_RC_2 = isset($REFERENCIASCOMERCIALES2["P_NOMBRE_EMPRESA_RC_2"])?$REFERENCIASCOMERCIALES2["P_NOMBRE_EMPRESA_RC_2"]:"";
$P_NOMBRE_CONTACTO_RC_2 = isset($REFERENCIASCOMERCIALES2["P_NOMBRE_CONTACTO_RC_2"])?$REFERENCIASCOMERCIALES2["P_NOMBRE_CONTACTO_RC_2"]:"";
$P_CELULAR_CONTACTO_RC_2 = isset($REFERENCIASCOMERCIALES2["P_CELULAR_CONTACTO_RC_2"])?$REFERENCIASCOMERCIALES2["P_CELULAR_CONTACTO_RC_2"]:"";
$P_TELEFONO_EMPRESA_RC_2 = isset($REFERENCIASCOMERCIALES2["P_TELEFONO_EMPRESA_RC_2"])?$REFERENCIASCOMERCIALES2["P_TELEFONO_EMPRESA_RC_2"]:"";
$P_NUMERO_EXTENSIO_CONTACTO_RC_2 = isset($REFERENCIASCOMERCIALES2["P_NUMERO_EXTENSIO_CONTACTO_RC_2"])?$REFERENCIASCOMERCIALES2["P_NUMERO_EXTENSIO_CONTACTO_RC_2"]:"";
$P_IMAIL_RC_2 = isset($REFERENCIASCOMERCIALES2["P_IMAIL_RC_2"])?$REFERENCIASCOMERCIALES2["P_IMAIL_RC_2"]:"";
$P_PAGINA_WEB_RC_2 = isset($REFERENCIASCOMERCIALES2["P_PAGINA_WEB_RC_2"])?$REFERENCIASCOMERCIALES2["P_PAGINA_WEB_RC_2"]:"";
$validaREFERENCIASCOMERCIALES2 = isset($REFERENCIASCOMERCIALES2["validaREFERENCIASCOMERCIALES2"])?$REFERENCIASCOMERCIALES2["validaREFERENCIASCOMERCIALES2"]:"";



/* REFERENCIAS COMERCIALES 1 */

$REFERENCIASCOMERCIALES3 = $proveedoresC->variable_REFERENCIASCOMERCIALES3();

$ROWotrosp12o= array('validaREFERENCIASCOMERCIALES3' =>'validaREFERENCIASCOMERCIALES3');
$datosREFERENCIASCOMERCIALES3 =$conexion->contadorporcentaje($REFERENCIASCOMERCIALES3,$ROWotrosp12o);




$P_NOMBRE_EMPRESA_RC_3 = isset($REFERENCIASCOMERCIALES3["P_NOMBRE_EMPRESA_RC_3"])?$REFERENCIASCOMERCIALES3["P_NOMBRE_EMPRESA_RC_3"]:"";
$P_NOMBRE_CONTACTO_RC_3 = isset($REFERENCIASCOMERCIALES3["P_NOMBRE_CONTACTO_RC_3"])?$REFERENCIASCOMERCIALES3["P_NOMBRE_CONTACTO_RC_3"]:"";
$P_CELULAR_CONTACTO_RC_3 = isset($REFERENCIASCOMERCIALES3["P_CELULAR_CONTACTO_RC_3"])?$REFERENCIASCOMERCIALES3["P_CELULAR_CONTACTO_RC_3"]:"";
$P_TELEFONO_EMPRESA_RC_3 = isset($REFERENCIASCOMERCIALES3["P_TELEFONO_EMPRESA_RC_3"])?$REFERENCIASCOMERCIALES3["P_TELEFONO_EMPRESA_RC_3"]:"";
$P_NUMERO_EXTENSION_RC_3 = isset($REFERENCIASCOMERCIALES3["P_NUMERO_EXTENSION_RC_3"])?$REFERENCIASCOMERCIALES3["P_NUMERO_EXTENSION_RC_3"]:"";
$P_IMAIL_RC_3 = isset($REFERENCIASCOMERCIALES3["P_IMAIL_RC_3"])?$REFERENCIASCOMERCIALES3["P_IMAIL_RC_3"]:"";
$P_PAGINA_WEB_RC_3 = isset($REFERENCIASCOMERCIALES3["P_PAGINA_WEB_RC_3"])?$REFERENCIASCOMERCIALES3["P_PAGINA_WEB_RC_3"]:"";
$validaREFERENCIASCOMERCIALES3 = isset($REFERENCIASCOMERCIALES3["validaREFERENCIASCOMERCIALES3"])?$REFERENCIASCOMERCIALES3["validaREFERENCIASCOMERCIALES3"]:""; 


